# Generated by Django 5.2.1 on 2025-05-31 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الجواب')),
                ('confidence', models.FloatField(default=0.0, verbose_name='مستوى الثقة')),
                ('sources', models.JSONField(default=list, verbose_name='المصادر')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإنشاء')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الجلسة')),
            ],
            options={
                'verbose_name': 'رسالة المحادثة',
                'verbose_name_plural': 'رسائل المحادثة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True, verbose_name='اسم الملف')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت المعالجة')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='عدد القطع')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مصدر المستند',
                'verbose_name_plural': 'مصادر المستندات',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='استعلام البحث')),
                ('results_count', models.IntegerField(default=0, verbose_name='عدد النتائج')),
                ('response_time', models.FloatField(default=0.0, verbose_name='وقت الاستجابة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البحث')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
            ],
            options={
                'verbose_name': 'استعلام البحث',
                'verbose_name_plural': 'استعلامات البحث',
                'ordering': ['-created_at'],
            },
        ),
    ]
