# Generated by Django 5.2.1 on 2025-05-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='مستوى الثقة'),
        ),
    ]
