# Generated by Django 5.2.1 on 2025-06-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_alter_chatmessage_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النموذج المستخدم'),
        ),
    ]
