# Generated by Django 5.2.1 on 2025-06-01 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_systemsettings_chatmessage_model_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'ordering': ['key'], 'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table='system_settings',
        ),
    ]
